### PR TITLE
Add in-memory NextShuffler

### PR DESCRIPTION
**Pull request by cxkoda**
This change is [Reviewable](https://reviewable.io/reviews/divergencetech/ethier/68)

### CODE REVIEW

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/68)* status: all files reviewed, 4 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/random/NextShufflerMemory.sol` line 92 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk1oZmDZDdIxl50KWn:-NJk1oZmDZDdIxl50KWo:b-mr7at7) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/contracts/random/NextShufflerMemory.sol#L92)):*
> ```Solidity
>     {
>         assembly {
>             rand := keccak256(add(state, 0x20), 0x40)
> ```

Is this the concatenation of the `entropy` and `shuffled` fields?
___
*[`tests/random/NextShufflerMemory.t.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk2uP35qpRq6WVf5_Q:-NJk2uP35qpRq6WVf5_R:b2nhjbn) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L1)):*
> ```Solidity
> // SPDX-License-Identifier: UNLICENSED
> ```

MIT
___
*[`tests/random/NextShufflerMemory.t.sol` line 9 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk3nauDtKiTxFzXuhT:-NJk3nauDtKiTxFzXuhU:bt51ghp) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L9)):*
> ```Solidity
> import {CSPRNG} from "../../contracts/random/CSPRNG.sol";
> 
> contract NextShufflerMemoryTest is Test {
> ```

You need to include a test that there are no stationary values (i.e. `shuffled[i] == i`). Have a look at the Go test for the non-memory equivalent for an explanation why. I think the probability of a stationary value is inversely proportional to the length of the input so a false-positive on the test is very unlikely.
___
*[`tests/random/NextShufflerMemory.t.sol` line 77 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk3VGU-a4x2kEnqEu4:-NJk3VGU-a4x2kEnqEu5:b-8rki6t) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L77)):*
> ```Solidity
> }
> 
> contract NextShufflerMemoryWithExternalRandomnessTest is
> ```

Where are you actually using this?

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/68)* status: all files reviewed, 5 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/random/NextShufflerMemory.sol` line 92 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk1oZmDZDdIxl50KWn:-NJoN1BA7GrhWzmuOpEC:b-n71jfx) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/contracts/random/NextShufflerMemory.sol#L92)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Is this the concatenation of the `entropy` and `shuffled` fields?
</blockquote></details>

Yes. I added a comment and a test to verify this.
___
*[`tests/random/NextShufflerMemory.t.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk2uP35qpRq6WVf5_Q:-NJoO4e426r1f6K7jEoz:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L1)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

MIT
</blockquote></details>

Done.
___
*[`tests/random/NextShufflerMemory.t.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk4l-HEmlUHcFnKx_D:-NJoO7NkCk0BQpbdJwb7:b-eeuy43) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L1)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Currently the CI just shows a `go_test` job. Can you please split these out so we can quickly confirm that Foundry tests are passing too?

Aside: we need to change the README re the north star because we Foundry is a clear winner on that front. Doesn't mean that there's no value in Go bindings, but we need to reframe the value add there.
</blockquote></details>

CI: done.

I would do the README rework as part of a large change where we separate the `ethier` binary and the `sol` library into two distinct packages/products.
___
*[`tests/random/NextShufflerMemory.t.sol` line 9 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk3nauDtKiTxFzXuhT:-NJoPGSLCSnTy6xf6JIs:b7g69up) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L9)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

You need to include a test that there are no stationary values (i.e. `shuffled[i] == i`). Have a look at the Go test for the non-memory equivalent for an explanation why. I think the probability of a stationary value is inversely proportional to the length of the input so a false-positive on the test is very unlikely.
</blockquote></details>

Adding our discussion for posterity here.

The probability for getting at least one stationary value approaches a constant in the limit of long lists and is roughly `P(numStationary > 0) ~ 0.63` (determined from a simple monte-carlo). Thus, the probability for not seeing any stationary values in repeated shuffles decreases with `P(0)^k`, where `k` is the number of repetitions. 
I added a test checking that our algorithm is able to produce stationary values by shuffling a small array with length 10 with a max number of repetitions of 1000. The probability of getting false-negatives is therefore well below `10^-100` and can be safely ignored in practice.
___
*[`tests/random/NextShufflerMemory.t.sol` line 77 at r1](https://reviewable.io/reviews/divergencetech/ethier/68#-NJk3VGU-a4x2kEnqEu4:-NJoQpmd76A8sX4gE3se:b-j6rygq) ([raw file](https://github.com/divergencetech/ethier/blob/406a8048ecd2d536eb908f9a74088f48e3ac7c31/tests/random/NextShufflerMemory.t.sol#L77)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Where are you actually using this?
</blockquote></details>

Nowhere yet since mod-sampling will provide good randomness for our usecase. My intention was to give users an alternative if they cannot use mod-sampling for some reason.

**Review by aschlosberg — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/68)* status: all files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`.github/workflows/test.yml` line 57 at r2](https://reviewable.io/reviews/divergencetech/ethier/68#-NJpGs4U23i2h1ljadw6:-NJpGs4U23i2h1ljadw7:b-lm60ux) ([raw file](https://github.com/divergencetech/ethier/blob/7c8673e8fcf0dbef13846312ec9106060bbe6356/.github/workflows/test.yml#L57)):*
> ```YAML
>           submodules: recursive
> 
>       - name: Setup Go
> ```

Why is Go needed for the Foundry tests?
___
*[`tests/random/NextShufflerMemory.t.sol` line 57 at r2](https://reviewable.io/reviews/divergencetech/ethier/68#-NJpHDjo6WzUEhs6tQAB:-NJpHDjo6WzUEhs6tQAC:bthr9cl) ([raw file](https://github.com/divergencetech/ethier/blob/7c8673e8fcf0dbef13846312ec9106060bbe6356/tests/random/NextShufflerMemory.t.sol#L57)):*
> ```Solidity
>         }
> 
>         assertFalse(true, "No stationary index found");
> ```

`assertTrue(false, …)` :smirk:

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/68)* status: all files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`.github/workflows/test.yml` line 57 at r2](https://reviewable.io/reviews/divergencetech/ethier/68#-NJpGs4U23i2h1ljadw6:-NJpkRt-9mNQMyC25fe1:b-th9md6) ([raw file](https://github.com/divergencetech/ethier/blob/7c8673e8fcf0dbef13846312ec9106060bbe6356/.github/workflows/test.yml#L57)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Why is Go needed for the Foundry tests?
</blockquote></details>

Need to build some helper binaries for forge tests.
___
*[`tests/random/NextShufflerMemory.t.sol` line 57 at r2](https://reviewable.io/reviews/divergencetech/ethier/68#-NJpHDjo6WzUEhs6tQAB:-NJpkYVc8U_xcUMMw6hU:bneqptx) ([raw file](https://github.com/divergencetech/ethier/blob/7c8673e8fcf0dbef13846312ec9106060bbe6356/tests/random/NextShufflerMemory.t.sol#L57)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`assertTrue(false, …)` :smirk: 
</blockquote></details>

:joy:

**Pull request merged**
