### PR TITLE
Remove the message generation from SignatureChecker

### PR DESCRIPTION
**Pull request by cxkoda**
# Intro
In the current state `SignatureChecker` handles two responsibilities:
- Message generation (such as `keccak256(abi.encodePacked(data, nonce))`)
- Message/Signature validation

The former should be not be covered by `SignatureChecker` following the SRP and should be left to the caller.
This will make the system more flexible - allowing different message generation procedures such as required by EIP-191 to be easily integrated.

# Implementation
- Message-type is `bytes32` (typically an output of `keccak256`)
- For signatures that should only be usable once, we will now track the `message` instead of `nonce`
- `validateSignature` for addresses has been removed completely following the SRP reasoning
- The logic for basic message generation has been moved to `TestableSignatureChecker`

*edit 01: Typo*

### CODE REVIEW

**Comment by divergencetech** [comment]
I agree with the SRP approach and especially the move to `usedMessages` over `usedNonces`; thank you for picking up on this.

I think we still need to provide standardised helper functions though, so should move message generation into a contract that inherits from `SignatureChecker` (not `TestableSignatureChecker`). My rationale is based in motivation (2); I think users of these contracts should have as much as possible abstracted unless they explicitly choose to delve deeper—if we provide an explicit address signer and respective checker then it doesn't need to be redone by every user.

What to call it though? ¯\_(ツ)_/¯

**Comment by cxkoda** [comment]
- The logic for message generation has now been moved to a separate `MessageGenerator` library.
- Further a convenience library was added, combining the functionalities of `MessageGenerator` and `SignatureChecker`. For now, that library was called  `SignedAllowance`. Better suggestions are more than welcome.

**Comment by divergencetech** [comment]
I think this is adding too much extra code (and hence complexity) in pursuit of the SRP. I think the "responsibility" can just as correctly be defined as "verify that a signature is correct of the payload being presented".

The `MessageGenerator` results in a significant amount of extra code merely to replace `keccak256(data)` and `keccak256(abi.encodePacked(data))`, and also adds indirection for the person reading it. My concern is that the indirection adds complexity and cognitive load that leads to a code base that's more prone to bugs. An end user is now also presented with the question of which of three contracts they choose from, which predisposes them to bugs in their own code and goes against the ethier vision.

**Comment by cxkoda** [comment]
I agree, moving this to a separate library (in the end having 3) is just overengineering and introduces too much overhead. I moved the relevant methods to the `SignedAllowance` library and removed `MessageGenerator` completely again.

I opted to keep `generateMessage` as separate functions though and not to inline them into `validateSignature`. This is to underline that message generation is conceptually split from signature verification. Also users might want to do this differently (in anticipation of #3) and/or use the generated messages somewhere else in their code.

Further I'm not really happy with the naming `SignedAllowance`, but I couldn't really come up with something better yet.

**Comment by cxkoda** [comment]
After reconsidering, I think there is still too much mental overhead in this version of the code - having two separate libraries. I'd opt discontinue this pull request in favor of #12.

**Comment by divergencetech** [comment]
Closing as superseded by https://github.com/divergencetech/ethier/pull/12

**Pull request closed without merging**
