### PR TITLE
Fix a bug in NextShuffler

### PR DESCRIPTION
**Pull request by cxkoda**
This change is [Reviewable](https://reviewable.io/reviews/divergencetech/ethier/87)

### CODE REVIEW

**Review by ARR4N — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/87)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`tests/random/nextshuffler_test.go` line 12 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYM76D-GS33ADhGOW:-NRJYM76D-GS33ADhGOX:b-8egegk) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L12)):*
> ```Go
> )
> 
> func factorial(num int) int {
> ```

You replaced this with MulRange so no longer needed
___
*[`tests/random/nextshuffler_test.go` line 104 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYS35DbCifZ-OxHwe:-NRJYS35DbCifZ-OxHwf:b-o5d673) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L104)):*
> ```Go
> 			shuffler.Reset(sim.Acc(0))
> 			got = runShuffling()
> 			if diff := cmp.Diff(want, got); diff != "" {
> ```

Why didn't this pick up the bug? That's what concerns me the most
___
*[`tests/random/nextshuffler_test.go` line 109 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYEv6BB2JisVCCztw:-NRJYEv78z_rjqqpuUNK:b-osk1vm) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L109)):*
> ```Go
> 
> 			inOrder := true
> 			for i, j := range gotShuffles {
> ```

Hehe nice

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/87)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`tests/random/nextshuffler_test.go` line 12 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYM76D-GS33ADhGOW:-NRPirs66Df7LPjRBQEx:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L12)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

You replaced this with MulRange so no longer needed
</blockquote></details>

Done.
___
*[`tests/random/nextshuffler_test.go` line 104 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYS35DbCifZ-OxHwe:-NRPhDz4Ccuyu2QYVPON:bihigl0) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L104)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Why didn't this pick up the bug? That's what concerns me the most
</blockquote></details>

The problem was not the shuffler itself but how it pulled random numbers from the PRNG (always zero). Our go implementation just reimplements the shuffling part but uses the same randomness that is provided through logging events. So it ends up with the same unshuffled list.

**Review by ARR4N — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/87)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @cxkoda)

___
*[`tests/random/nextshuffler_test.go` line 104 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYS35DbCifZ-OxHwe:-NRPk4yTDOwwU8syrnHu:b3n1oqd) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L104)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

The problem was not the shuffler itself but how it pulled random numbers from the PRNG (always zero). Our go implementation just reimplements the shuffling part but uses the same randomness that is provided through logging events. So it ends up with the same unshuffled list.
</blockquote></details>

That's my fault! Should've listened to https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html?m=1

Please can you add an explicit test of the output? I know it'll be copied directly from the output, but we least we'll see the values and know that there's nothing weird.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/87)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @aschlosberg)

___
*[`tests/random/nextshuffler_test.go` line 104 at r3](https://reviewable.io/reviews/divergencetech/ethier/87#-NRJYS35DbCifZ-OxHwe:-NRPvfdF-qQ5rzAVpED6:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/0121e4a2cbdeb4ed4342b242a1f96135515192e3/tests/random/nextshuffler_test.go#L104)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

That's my fault! Should've listened to https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html?m=1

Please can you add an explicit test of the output? I know it'll be copied directly from the output, but we least we'll see the values and know that there's nothing weird.
</blockquote></details>

Done.

**Pull request merged**
