### PR TITLE
Add appending as base64 to DynamicBuffer

### PR DESCRIPTION
**Pull request by cxkoda**
This change is [Reviewable](https://reviewable.io/reviews/divergencetech/ethier/60)

### CODE REVIEW

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/60)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/utils/DynamicBuffer.sol` line 122 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGQzw6321wPLM24w94X:-NGQzw6321wPLM24w94Y:bsm10gy) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L122)):*
> ```Solidity
>             // Multiply by 4/3 rounded up.
>             // The `shl(2, ...)` is equivalent to multiplying by 4.
>             encodedLength := shl(2, div(add(dataLength, 2), 3))
> ```

Does having the `div` inside risk actually getting `floor` instead of `ceil` like your "rounded up" comment suggests you want?

`encodedLength := div(shl(2, add(dataLength, 2)), 3)`?

For all I know, mine introduces that problem :rofl:
___
*[`contracts/utils/DynamicBuffer.sol` line 128 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-U_lA3uqTYTRNVE8:-NGR-U_lA3uqTYTRNVE9:bpryqh4) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L128)):*
> ```Solidity
>                 encodedLength := sub(
>                     encodedLength,
>                     add(iszero(iszero(r)), eq(r, 1))
> ```

Please add a comment with the basic logic / arithmetic
___
*[`contracts/utils/DynamicBuffer.sol` line 142 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-qIm2JVxjHtvG_oU:-NGR-qIm2JVxjHtvG_oV:byzfpoz) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L142)):*
> ```Solidity
>             // We will rewrite the free memory pointer at `0x40` later with
>             // the allocated size.
>             // The magic constant 0x0230 will translate "-_" + "+/".
> ```

Nice! Although please move this line to where it's actually used.
___
*[`contracts/utils/DynamicBuffer.sol` line 171 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0CLzCRglaJUJlZ6H:-NGR0CLzCRglaJUJlZ6I:b-mlm0i5) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L171)):*
> ```Solidity
>                     ptr := add(ptr, 4) // Advance 4 bytes.
>                     // prettier-ignore
>                     if iszero(lt(data, end)) { break }
> ```

Why put this here and not in the for loop? Similarly for the `data` increments?
___
*[`tests/utils/dynamicbuffer_test.go` line 8 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0N3B2Bv_OyZDVbQH:-NGR0N3B2Bv_OyZDVbQI:b-90b6h8) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L8)):*
> ```Go
> 	"testing"
> 
> 	b64 "encoding/base64"
> ```

https://zchee.github.io/golang-wiki/CodeReviewComments/#imports

`base64` is a common package and it signals to readers that they know what it does. If someone sees `b64.StdEncoding` they assume it's a new package that they have to inspect. Similarly, if someone goes to public `godoc` and searches for `b64` they won't be able to find it.
___
*[`tests/utils/dynamicbuffer_test.go` line 139 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0ofYBdFXCrr7E4bv:-NGR0ofYBdFXCrr7E4bw:b-eu84p3) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L139)):*
> ```Go
> 
> func base64Len(data string) int64 {
> 	return int64((len(data) + 2) / 3 * 4)
> ```

Use https://pkg.go.dev/encoding/base64#Encoding.EncodedLen
___
*[`tests/utils/dynamicbuffer_test.go` line 153 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0tfMAVSGff3Lbxfn:-NGR0tfMAVSGff3Lbxfo:b-qssgoc) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L153)):*
> ```Go
> 	}
> 	const (
> 		testStrWithoutPadding = "This is a really long test string that with padding"
> ```

`that with padding`?
___
*[`tests/utils/dynamicbuffer_test.go` line 159 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR14Dy4D9x7ms6LcjE:-NGR14Dy4D9x7ms6LcjF:b-c8gs1) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L159)):*
> ```Go
> 
> 	if base64Len(testStrWithoutPadding) != base64LenUnpadded(testStrWithoutPadding) {
> 		t.Fatalf("Test string has incorrect length: %s", testStrWithoutPadding)
> ```

This error and the next need to be more descriptive. Ideally, someone reading it should be able to diagnose the problem from just the message. TL;DR why is the length incorrect?

https://zchee.github.io/golang-wiki/CodeReviewComments/#useful-test-failures
___
*[`tests/utils/dynamicbuffer_test.go` line 242 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR3Ps72a-ANPOsfJtY:-NGR3Ps72a-ANPOsfJtZ:b-7tq0gb) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L242)):*
> ```Go
> 		},
> 		{
> 			name:         "Double (unpadded) append with noPadding ",
> ```

What do you mean by `padded` and `unpadded` vs `noPadding`?
___
*[`tests/utils/dynamicbuffer_test.go` line 275 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR2U1TBvpLJmPnu0VJ:-NGR2U1TBvpLJmPnu0VK:b-fw3ww3) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L275)):*
> ```Go
> 			got, err := dynBuf.AllocateAndAppendRepeatedBase64(nil, big.NewInt(tt.capacity), []byte(tt.appendString), big.NewInt(tt.repetitions), tt.fileSafe, tt.noPadding)
> 
> 			if diff := errdiff.Check(err, tt.errDiffAgainst); diff != "" {
> ```

(fyi) I wrote https://pkg.go.dev/github.com/divergencetech/ethier/ethtest/revert for this, but it doesn't cater for not reverting so isn't appropriate here.
___
*[`tests/utils/dynamicbuffer_test.go` line 283 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR1aTf85MNxn326oek:-NGR1aTf85MNxn326oel:bbhir3n) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L283)):*
> ```Go
> 			}
> 
> 			want := ""
> ```

`var want string`
___
*[`tests/utils/dynamicbuffer_test.go` line 284 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR26UuAZWwogJP1V04:-NGR26UuAZWwogJP1V05:bafjj8y) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L284)):*
> ```Go
> 
> 			want := ""
> 			for r := int64(0); r < tt.repetitions; r++ {
> ```

`i` not `r` as it's the typical loop variable. Also, make `tt.repetitions` an `int` so you don't have to be explicit about using `int64` here:

`for i := 0; i < tt.repetitions; i++`
___
*[`tests/utils/dynamicbuffer_test.go` line 285 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR1kvW4MEFposBCVar:-NGR1kvW4MEFposBCVas:b-zdkj5y) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L285)):*
> ```Go
> 			want := ""
> 			for r := int64(0); r < tt.repetitions; r++ {
> 				want = want + b64.StdEncoding.EncodeToString([]byte(tt.appendString))
> ```

(fyi) If you were doing this in production code, see `strings.Builder` and `bytes.Builder` as they're more efficient.
___
*[`tests/utils/dynamicbuffer_test.go` line 298 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR2gx-27frWyGfIuUK:-NGR2gx-27frWyGfIuUL:bb3zxaw) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L298)):*
> ```Go
> 
> 			if got != want {
> 				t.Errorf("AllocateAndAppendRepeatedBase64(%d, %q, %d, %v, %v) got %q; want %q", tt.capacity, tt.appendString, tt.repetitions, tt.fileSafe, tt.noPadding, got, want)
> ```

(fyi) `%v` is completely fine, but so you know, `%t` (for true) is the boolean verb. Not to be confused with `%T` for the type, and `%b` for binary.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/60)* status: 1 of 3 files reviewed, 13 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/utils/DynamicBuffer.sol` line 122 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGQzw6321wPLM24w94X:-NGRGw8T2UPFDbqyhZOd:b-s1qaei) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L122)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Does having the `div` inside risk actually getting `floor` instead of `ceil` like your "rounded up" comment suggests you want?

`encodedLength := div(shl(2, add(dataLength, 2)), 3)`?

For all I know, mine introduces that problem :rofl:
</blockquote></details>

The `add(..,2)` does the trick since`divCeil(x,y) = divFloor(x + (y-1), y)`

I changed the comment since it was misleading. 
___
*[`contracts/utils/DynamicBuffer.sol` line 128 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-U_lA3uqTYTRNVE8:-NGRIOLZ8x94sj3TChQT:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L128)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Please add a comment with the basic logic / arithmetic
</blockquote></details>

Done.
___
*[`contracts/utils/DynamicBuffer.sol` line 142 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-qIm2JVxjHtvG_oU:-NGRId-s7hQ-MPeBPP1u:b-r444k8) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L142)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Nice! Although please move this line to where it's actually used.
</blockquote></details>

It's used inside the `for` loop that follows. The next instructions before the loop specify the iteration range, so it makes sense to keep them closer to the loop than the definition of the lookup table.
___
*[`contracts/utils/DynamicBuffer.sol` line 171 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0CLzCRglaJUJlZ6H:-NGRJA3M8OFo99PbgAw5:b-x9wuxn) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L171)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Why put this here and not in the for loop? Similarly for the `data` increments?
</blockquote></details>

It's slightly more efficient like this.
___
*[`tests/utils/dynamicbuffer_test.go` line 8 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0N3B2Bv_OyZDVbQH:-NGRL_6b9UgdLM_amw8q:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L8)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

https://zchee.github.io/golang-wiki/CodeReviewComments/#imports

`base64` is a common package and it signals to readers that they know what it does. If someone sees `b64.StdEncoding` they assume it's a new package that they have to inspect. Similarly, if someone goes to public `godoc` and searches for `b64` they won't be able to find it.
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 139 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0ofYBdFXCrr7E4bv:-NGRM0EL0GqjEXwJ7Cyr:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L139)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Use https://pkg.go.dev/encoding/base64#Encoding.EncodedLen
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 153 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR0tfMAVSGff3Lbxfn:-NGRR-RA8iXnv1_-nruJ:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L153)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`that with padding`?
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 159 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR14Dy4D9x7ms6LcjE:-NGRR6dS2eWE4o6IGfnk:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L159)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

This error and the next need to be more descriptive. Ideally, someone reading it should be able to diagnose the problem from just the message. TL;DR why is the length incorrect?

https://zchee.github.io/golang-wiki/CodeReviewComments/#useful-test-failures
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 242 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR3Ps72a-ANPOsfJtY:-NGRRBwR7VW6_deGZ2U6:b-h8m3vg) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L242)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

What do you mean by `padded` and `unpadded` vs `noPadding`?
</blockquote></details>

`(padded/unpadded)` refers to the test string that will be used, whereas `noPadding` is a parameter of the method that is tested.
I changed it to the variable name.
___
*[`tests/utils/dynamicbuffer_test.go` line 275 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR2U1TBvpLJmPnu0VJ:-NGRRnUm84M4-5NbfwA5:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L275)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(fyi) I wrote https://pkg.go.dev/github.com/divergencetech/ethier/ethtest/revert for this, but it doesn't cater for not reverting so isn't appropriate here.
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 283 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR1aTf85MNxn326oek:-NGRRtAr0SrgsQGJM1Tb:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L283)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`var want string`
</blockquote></details>

Done.
___
*[`tests/utils/dynamicbuffer_test.go` line 284 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR26UuAZWwogJP1V04:-NGRSPZz1biejw87YKOn:boytf60) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L284)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`i` not `r` as it's the typical loop variable. Also, make `tt.repetitions` an `int` so you don't have to be explicit about using `int64` here:

`for i := 0; i < tt.repetitions; i++`
</blockquote></details>

The `int64` was deliberate to have the same variable type as the contract method.
But in hindsight it is more readable to replace it with `int` and cast once for the method call.
___
*[`tests/utils/dynamicbuffer_test.go` line 285 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR1kvW4MEFposBCVar:-NGRSkMg1IeK_6FwC1af:bvzdlp8) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L285)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(fyi) If you were doing this in production code, see `strings.Builder` and `bytes.Builder` as they're more efficient.
</blockquote></details>

Oh interesting! Thanks you for the tip.

**Review by aschlosberg — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/60)* status: all files reviewed, 1 unresolved discussion (waiting on @cxkoda)

___
*[`contracts/utils/DynamicBuffer.sol` line 142 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-qIm2JVxjHtvG_oU:-NGrGgEM5hhcRrI6WWnO:bclk54z) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L142)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

It's used inside the `for` loop that follows. The next instructions before the loop specify the iteration range, so it makes sense to keep them closer to the loop than the definition of the lookup table.
</blockquote></details>

Sorry, I just meant the comment, not the code.
___
*[`tests/utils/dynamicbuffer_test.go` line 242 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR3Ps72a-ANPOsfJtY:-NGrJPpPArqkC67a0eKs:bayj95j) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L242)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

`(padded/unpadded)` refers to the test string that will be used, whereas `noPadding` is a parameter of the method that is tested.
I changed it to the variable name.
</blockquote></details>

Gotcha, makes sense!
___
*[`tests/utils/dynamicbuffer_test.go` line 284 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR26UuAZWwogJP1V04:-NGrHEbj0-waCZzd74uV:b-eap5vr) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/tests/utils/dynamicbuffer_test.go#L284)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

The `int64` was deliberate to have the same variable type as the contract method.
But in hindsight it is more readable to replace it with `int` and cast once for the method call.
</blockquote></details>

Yeah it's a pain that the `big.Int` can't work with `int` and just assume that it's an `int64` because presumably it can't compile for 32bit machines.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/60)* status: all files reviewed, 1 unresolved discussion (waiting on @aschlosberg)

___
*[`contracts/utils/DynamicBuffer.sol` line 142 at r2](https://reviewable.io/reviews/divergencetech/ethier/60#-NGR-qIm2JVxjHtvG_oU:-NGunNx-EdR6I4--6_h5:b-y7dw18) ([raw file](https://github.com/divergencetech/ethier/blob/a0c2e73fd98d885ceb9875f624f2e5f194666aa1/contracts/utils/DynamicBuffer.sol#L142)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Sorry, I just meant the comment, not the code.
</blockquote></details>

Ah gotcha! Sorry.

**Pull request merged**
