### PR TITLE
Add util libs

### PR DESCRIPTION
**Pull request by cxkoda**
This change is [Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)

### CODE REVIEW

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 11 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)* status: 10 of 19 files reviewed, 11 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/utils/BMP.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5_Q4jC-mO2K-c26ce:-NH5_Q4jC-mO2K-c26cf:b2nhjbn) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L1)):*
> ```Solidity
> // SPDX-License-Identifier: UNLICENSED
> ```

MIT
___
*[`contracts/utils/BMP.sol` line 16 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5_fUU7qnxFCjyT4IJ:-NH5_fUU7qnxFCjyT4IK:b-25lewf) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L16)):*
> ```Solidity
>     using RawData for bytes;
> 
>     error InvalidDimensions(uint256 want, uint256 got);
> ```

(nit) `want` and `got` are very much Go terms; I think `expected` and `actual` are more appropriate.
___
*[`contracts/utils/BMP.sol` line 119 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5a8Pb43b4ALYUGvhm:-NH5a8Pc8622dYWKAUuO:b-q5coeh) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L119)):*
> ```Solidity
>         buf.writeUint32LE(0x2a, 0x01);
> 
>         // I've decided to use raw pixels instead of run-length encoding for
> ```

(nit) `We use raw pixels…`
___
*[`contracts/utils/Image.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5aSf39fvJyvC230r_:-NH5aSf39fvJyvC230ra:b2nhjbn) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L1)):*
> ```Solidity
> // SPDX-License-Identifier: UNLICENSED
> ```

MIT
___
*[`contracts/utils/Image.sol` line 33 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5aec45Hxc9Fh4e1Vs:-NH5aec45Hxc9Fh4e1Vt:b-8ajir4) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L33)):*
> ```Solidity
>     function fill(bytes memory bgrPixels, uint24 rgb) internal pure {
>         assembly {
>             let bgr := shl(
> ```

Obviously :rofl:

Please give a basic explanation; e.g. why 232?
___
*[`contracts/utils/Image.sol` line 98 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5b36c8RtaeKdj1XV4:-NH5b36c8RtaeKdj1XV5:b-83sjoh) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L98)):*
> ```Solidity
>             // Spacing the color channel values across the 256 bit word.
>             // | 0 (13B) | R (1B) | 0 (8B) | G (1B) | 0 (8B) | R (1B) |
>             // This allows all channels to be blended in a single operation.
> ```

Nice!
___
*[`contracts/utils/Image.sol` line 137 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bADWACs3VFmZc-xF:-NH5bADWACs3VFmZc-xG:b4zchnh) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L137)):*
> ```Solidity
>      */
>     function alphaBlend(
>         bytes memory bgrPixels,
> ```

These names can be misleading because someone could interpret `bg` as background, not blue-green. I think `backBgrPixels` and `frontAbgrPixels`, and possibly even drop the `Pixels` suffix.
___
*[`contracts/utils/Image.sol` line 269 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bnxvD2EaYb7sDar1:-NH5bnxvD2EaYb7sDar2:b9xd8xx) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L269)):*
> ```Solidity
>      * @param scalingFactor The scaling factor.
>      */
>     function appendSafeScaled(
> ```

Technically these are the `unsafe` ones because they don't perform checks. I only just thought of this so I'm not going back over already-reviewed code, but applies to all other functions too.
___
*[`forge-testing/convertHexFile/main.go` line 3 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5c9Qy92KRghD2Vbxi:-NH5c9Qy92KRghD2Vbxj:b2zydmk) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L3)):*
> ```Go
> // The convertHexFile binary convert a file containing a hex string into
> // a file containing the content of the hex string.
> ```

(nit) No space here
___
*[`forge-testing/convertHexFile/main.go` line 13 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5cL8IChmoyTw5HNUs:-NH5cL8IChmoyTw5HNUt:br9qyfb) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L13)):*
> ```Go
> 	"strings"
> 
> 	"github.com/golang/glog"
> ```

No need to use `glog` here as the stdlib `log` package will do. Or even just `fmt.Fprint(os.Stderr, err)` then `os.Exit(1)`.
___
*[`forge-testing/convertHexFile/main.go` line 29 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5cd1EBFbgdqR_u5uW:-NH5cd1EBFbgdqR_u5uX:b-vasxcm) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L29)):*
> ```Go
> 	}
> 
> 	b, err := io.ReadAll(f)
> ```

This requires reading potentially very large files entirely into memory. You can use an intermediate `buf []byte` of even length to read, convert, and write to the output.
___
*[`forge-testing/convertHexFile/main.go` line 44 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5crem529KI9nNBBXj:-NH5crem529KI9nNBBXk:b7t092r) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L44)):*
> ```Go
> 		return fmt.Errorf("os.Create(%q): %w", path, err)
> 	}
> 	defer f.Close()
> ```

`f.Close()` returns an error that MUST be checked when writing because it may try to flush a buffer to disk and that could be an error. The common pattern for this is:

```Go
func foo() (retErr error){
…
  defer func() {
    if err := f.Close(); retErr == nil {
      retErr = err
    }
  }()
…
}
```

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)* status: 8 of 19 files reviewed, 12 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/utils/BMP.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5_Q4jC-mO2K-c26ce:-NH5eWM772wJsb50l8wE:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L1)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

MIT
</blockquote></details>

Done.
___
*[`contracts/utils/BMP.sol` line 16 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5_fUU7qnxFCjyT4IJ:-NH5fAdJ0ENKc6nCu7CD:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L16)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(nit) `want` and `got` are very much Go terms; I think `expected` and `actual` are more appropriate.
</blockquote></details>

Done.
___
*[`contracts/utils/BMP.sol` line 119 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5a8Pb43b4ALYUGvhm:-NH5fheNBjNxNfG8Zp_f:brfj8j7) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L119)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(nit) `We use raw pixels…`
</blockquote></details>

https://etherscan.io/address/0xd31fc221d2b0e0321c43e9f6824b26ebfff01d7d#code#F18#L98 :stuck_out_tongue_winking_eye: 
___
*[`contracts/utils/Image.sol` line 1 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5aSf39fvJyvC230r_:-NH5ecZB3-A3arrNg-sq:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L1)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

MIT
</blockquote></details>

Done.
___
*[`contracts/utils/Image.sol` line 33 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5aec45Hxc9Fh4e1Vs:-NH5f3twEmA4G5aiZ17E:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L33)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Obviously :rofl:

Please give a basic explanation; e.g. why 232?
</blockquote></details>

Done.
___
*[`contracts/utils/Image.sol` line 137 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bADWACs3VFmZc-xF:-NH5gAmQ2TOemMkNyPn2:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L137)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

These names can be misleading because someone could interpret `bg` as background, not blue-green. I think `backBgrPixels` and `frontAbgrPixels`, and possibly even drop the `Pixels` suffix.
</blockquote></details>

Done.
___
*[`contracts/utils/Image.sol` line 269 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bnxvD2EaYb7sDar1:-NH5gNLBBIJW6gKdJwM7:b-pnhr4h) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L269)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Technically these are the `unsafe` ones because they don't perform checks. I only just thought of this so I'm not going back over already-reviewed code, but applies to all other functions too.
</blockquote></details>

See below.
___
*[`contracts/utils/Image.sol` line 276 at r2](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5gL0G3ObfZV7r2m6r:-NH5gL0G3ObfZV7r2m6s:bal17hb) ([raw file](https://github.com/divergencetech/ethier/blob/31afe69c9fdfb7fe2734d30ce12de013a7469238/contracts/utils/Image.sol#L276)):*
> ```Solidity
>         uint256 scalingFactor
>     ) internal pure {
>         buffer.checkOverflow(bgr.length * scalingFactor * scalingFactor);
> ```

It is checked here.
___
*[`forge-testing/convertHexFile/main.go` line 3 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5c9Qy92KRghD2Vbxi:-NH5gT68EtnLxS7n1y3L:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L3)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(nit) No space here
</blockquote></details>

Done.
___
*[`forge-testing/convertHexFile/main.go` line 13 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5cL8IChmoyTw5HNUs:-NH5ga0PASGWuk4JWV5U:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L13)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

No need to use `glog` here as the stdlib `log` package will do. Or even just `fmt.Fprint(os.Stderr, err)` then `os.Exit(1)`.
</blockquote></details>

Done.
___
*[`forge-testing/convertHexFile/main.go` line 29 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5cd1EBFbgdqR_u5uW:-NH5hWgz5Mv5HBTiBy4J:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L29)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

This requires reading potentially very large files entirely into memory. You can use an intermediate `buf []byte` of even length to read, convert, and write to the output.
</blockquote></details>

Done.
___
*[`forge-testing/convertHexFile/main.go` line 44 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5crem529KI9nNBBXj:-NH5hF23AYer5l4fvwdj:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/forge-testing/convertHexFile/main.go#L44)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`f.Close()` returns an error that MUST be checked when writing because it may try to flush a buffer to disk and that could be an error. The common pattern for this is:

```Go
func foo() (retErr error){
…
  defer func() {
    if err := f.Close(); retErr == nil {
      retErr = err
    }
  }()
…
}
```
</blockquote></details>

Done.

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)* status: 13 of 19 files reviewed, 5 unresolved discussions (waiting on @cxkoda)

___
*[`contracts/utils/BMP.sol` line 119 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5a8Pb43b4ALYUGvhm:-NHPYHwnAmg-uz6F8Aot:b-o8yi7v) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/BMP.sol#L119)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

https://etherscan.io/address/0xd31fc221d2b0e0321c43e9f6824b26ebfff01d7d#code#F18#L98 :stuck_out_tongue_winking_eye: 
</blockquote></details>

Haha I was wondering how much of this came from Brotchain! Still, it's now part of something collaborative.
___
*[`contracts/utils/Image.sol` line 137 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bADWACs3VFmZc-xF:-NHPYhj2590sDvKUMwYC:b-ytwg8a) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L137)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now I'm even more confused :rofl: by `bgBg`r! How do you feel about `backBgr` and `foreAbgr`?
___
*[`contracts/utils/Image.sol` line 269 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bnxvD2EaYb7sDar1:-NHPYsyq0OR6yQhaO5sF:b-8ayeln) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L269)):*
<details><summary><i>Previously, cxkoda (David Huber) wrote…</i></summary><blockquote>

See below.
</blockquote></details>

Ahhh!
___
*[`forge-testing/convertHexFile/main.go` line 22 at r3](https://reviewable.io/reviews/divergencetech/ethier/66#-NHQ3kaG1xW1YyBhxzjP:-NHQ3kaG1xW1YyBhxzjQ:b31wfq9) ([raw file](https://github.com/divergencetech/ethier/blob/56756041ec6fc159ebbae687025f3b8c0e005325/forge-testing/convertHexFile/main.go#L22)):*
> ```Go
> }
> 
> func convertHexFile(path string) (retErr error) {
> ```

I've sent you https://github.com/divergencetech/ethier/pull/67 with suggestions for this file.
___
*[`forge-testing/isValidBMP/main.go` line 36 at r3](https://reviewable.io/reviews/divergencetech/ethier/66#-NHPwjyyA3eD0-PbVwgb:-NHPwjyyA3eD0-PbVwgc:b-r712xn) ([raw file](https://github.com/divergencetech/ethier/blob/56756041ec6fc159ebbae687025f3b8c0e005325/forge-testing/isValidBMP/main.go#L36)):*
> ```Go
> 
> 	_, err = bmp.Decode(file)
> 	if err != nil {
> ```

`if _, err := bmp.Decode(file); err != nil {`

**Review by aschlosberg — APPROVED** [review]
LGTM pending merge of #67 into here

> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66#-:-NHQ6TSS2jOFSf1XWg1M:b2rpg5f)* status: 13 of 19 files reviewed, 5 unresolved discussions (waiting on @cxkoda)

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)* status: 13 of 19 files reviewed, 5 unresolved discussions (waiting on @aschlosberg)

___
*[`contracts/utils/Image.sol` line 137 at r1](https://reviewable.io/reviews/divergencetech/ethier/66#-NH5bADWACs3VFmZc-xF:-NHQBzws9VEuhExeObUL:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/086bfe859af3234ac81f0451702a2af67a3cc415/contracts/utils/Image.sol#L137)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Now I'm even more confused :rofl: by `bgBg`r! How do you feel about `backBgr` and `foreAbgr`?
</blockquote></details>

Done.
___
*[`forge-testing/isValidBMP/main.go` line 36 at r3](https://reviewable.io/reviews/divergencetech/ethier/66#-NHPwjyyA3eD0-PbVwgb:-NHQCjeB8pk3WDBLuHub:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/56756041ec6fc159ebbae687025f3b8c0e005325/forge-testing/isValidBMP/main.go#L36)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

`if _, err := bmp.Decode(file); err != nil {`
</blockquote></details>

Done.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/66)* status: 11 of 19 files reviewed, 5 unresolved discussions (waiting on @aschlosberg)

___
*[`forge-testing/convertHexFile/main.go` line 22 at r3](https://reviewable.io/reviews/divergencetech/ethier/66#-NHQ3kaG1xW1YyBhxzjP:-NHQCs85CgkbpYxnDW67:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/56756041ec6fc159ebbae687025f3b8c0e005325/forge-testing/convertHexFile/main.go#L22)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I've sent you https://github.com/divergencetech/ethier/pull/67 with suggestions for this file.
</blockquote></details>

Done.

**Pull request merged**
