### PR TITLE
Don't use the internal image endpoint if the metadata already contains an URL

### PR DESCRIPTION
**Pull request by cxkoda**
This change is [Reviewable](https://reviewable.io/reviews/divergencetech/ethier/55)

### CODE REVIEW

**Review by aschlosberg — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/55)* status: all files reviewed, 3 unresolved discussions (waiting on @cxkoda)

___
*[`erc721/server_test.go` line 81 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9WhQqd-F6bG1sG3kRp:-N9WhQqd-F6bG1sG3kRq:b833vw2) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L81)):*
> ```Go
> 	)
> 
> 	cases := []struct {
> ```

Typically this variable is called `tests` and the loop variable, `tt`.
___
*[`erc721/server_test.go` line 83 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9WhoWz7QwA3rXraVmj:-N9WhYa0BC_J-c19c-uc:b-cyd803) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L83)):*
> ```Go
> 	cases := []struct {
> 		UseExternalImageURL bool
> 		ExternalImageURL    string
> ```

As these are logically coupled, I think drop the `bool` and change your `ignore` if block to be based on `tt.ExternalImageURL == ""`; i.e. `{true, non-empty string}` is an undefined test behaviour so we shouldn't allow it.
___
*[`erc721/server_test.go` line 95 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9Wi0vj0DnwTXVqZp4b:-N9Wi0vj0DnwTXVqZp4c:b-9tppju) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L95)):*
> ```Go
> 
> 	for _, c := range cases {
> ```

Add a `name string` field to the tests and call `t.Run(tt.name, func(t *testing.T) {` here. Without this, the `return` in the `if t.Failed()` will exit all tests, not just the current one.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/55)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @aschlosberg)

___
*[`erc721/server_test.go` line 81 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9WhQqd-F6bG1sG3kRp:-N9Wvi5q1NyGImz9qBTK:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L81)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Typically this variable is called `tests` and the loop variable, `tt`.
</blockquote></details>

Done.
___
*[`erc721/server_test.go` line 83 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9WhoWz7QwA3rXraVmj:-N9WvseaEGXxQoLv4qud:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L83)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

As these are logically coupled, I think drop the `bool` and change your `ignore` if block to be based on `tt.ExternalImageURL == ""`; i.e. `{true, non-empty string}` is an undefined test behaviour so we shouldn't allow it.
</blockquote></details>

Done.
___
*[`erc721/server_test.go` line 95 at r1](https://reviewable.io/reviews/divergencetech/ethier/55#-N9Wi0vj0DnwTXVqZp4b:-N9WvuxYEIvX0iGiZ0-6:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/03d48d4dd93b85e1412d349245d1603034a458ba/erc721/server_test.go#L95)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Add a `name string` field to the tests and call `t.Run(tt.name, func(t *testing.T) {` here. Without this, the `return` in the `if t.Failed()` will exit all tests, not just the current one.
</blockquote></details>

Done.

**Review by aschlosberg — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/55)* status: all files reviewed, 6 unresolved discussions (waiting on @aschlosberg and @cxkoda)

___
*[`erc721/server_test.go` line 108 at r2](https://reviewable.io/reviews/divergencetech/ethier/55#-N9X0Vh_2ESuY1FvayS4:-N9X0Vh_2ESuY1FvayS5:b-9nbh8a) ([raw file](https://github.com/divergencetech/ethier/blob/6467c2c025964c4dd72e44e48e6208a734249cff/erc721/server_test.go#L108)):*
> ```Go
> 					}
> 
> 					if tt.ExternalImageURL != "" {
> ```

This doesn't require an if statement any more. You can just collapse it all into:

```Go
md := Metadata{
  Name: fmt.Sprintf("Token %s", id),
  Image: tt.ExternalImageURL,
}
```
___
*[`erc721/server_test.go` line 151 at r2](https://reviewable.io/reviews/divergencetech/ethier/55#-N9X0crb10wvoloCoo4L:-N9X0crb10wvoloCoo4M:blbsmd8) ([raw file](https://github.com/divergencetech/ethier/blob/6467c2c025964c4dd72e44e48e6208a734249cff/erc721/server_test.go#L151)):*
> ```Go
> 						}
> 
> 						var ignore cmp.Option
> ```

(nit) A more idiomatic way to do this is with an `Option` slice that you append to:

```Go
var opts []cmp.Option
if tt.ExternalImageURL == "" {
  opts = append(opts, cmpopts.Ignore…)
}

…

… cmp.Diff(want, got, opts...) …
```

This makes it more robust to refactoring (also why you use `append` even though you know that it's an empty slice to begin with).
___
*[`erc721/server_test.go` line 152 at r2](https://reviewable.io/reviews/divergencetech/ethier/55#-N9X0ZneANjZ0vnoTkJ_:-N9X0ZneANjZ0vnoTkJa:brk4l2u) ([raw file](https://github.com/divergencetech/ethier/blob/6467c2c025964c4dd72e44e48e6208a734249cff/erc721/server_test.go#L152)):*
> ```Go
> 
> 						var ignore cmp.Option
> 						if tt.ExternalImageURL == "" {
> ```

Please add a comment why.

**Review by cxkoda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/divergencetech/ethier/55)* status: all files reviewed, 6 unresolved discussions (waiting on @aschlosberg and @cxkoda)

___
*[`erc721/server_test.go` line 108 at r2](https://reviewable.io/reviews/divergencetech/ethier/55#-N9X0Vh_2ESuY1FvayS4:-N9X1pH63Hvgf24V0z_f:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/6467c2c025964c4dd72e44e48e6208a734249cff/erc721/server_test.go#L108)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

This doesn't require an if statement any more. You can just collapse it all into:

```Go
md := Metadata{
  Name: fmt.Sprintf("Token %s", id),
  Image: tt.ExternalImageURL,
}
```
</blockquote></details>

Done.
___
*[`erc721/server_test.go` line 151 at r2](https://reviewable.io/reviews/divergencetech/ethier/55#-N9X0crb10wvoloCoo4L:-N9X262O41uKIxHJKlou:b-896fix) ([raw file](https://github.com/divergencetech/ethier/blob/6467c2c025964c4dd72e44e48e6208a734249cff/erc721/server_test.go#L151)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

(nit) A more idiomatic way to do this is with an `Option` slice that you append to:

```Go
var opts []cmp.Option
if tt.ExternalImageURL == "" {
  opts = append(opts, cmpopts.Ignore…)
}

…

… cmp.Diff(want, got, opts...) …
```

This makes it more robust to refactoring (also why you use `append` even though you know that it's an empty slice to begin with).
</blockquote></details>

Done.

**Pull request merged**
